### ISSUE TITLE
Handle not found pages gracefully

### ISSUE THREAD

**Issue by kettanaito** [frontarm/navi#115]
Hi.

I apologize if I bring it up as a duplicate, but I've gone through all related issues and haven't found a solution.

## Expected behavior

I want to be able to control "not found" route behavior and render a dedicated react component (page) in that case. This is how I would expect it to work:

```jsx
// routes.js
import { mount, route } from 'navi'
import Frontpage from './pages/Frontpage'
import About from './pages/About'
import Page404 from './pages/Page404'

export default mount({
  '/': route({ view: <Frontpage /> }),
  '/about': route({ view: <About /> }),
  '*': route({ view: <Page404 /> }),
})
```

```js
// App.jsx
import React, { Suspense } from 'react'
import ReactDOM from 'react-dom'
import { Router, View } from 'react-navi'
import routes from './routes'

const render = module.hot ? ReactDOM.hydrate : ReactDOM.render

render(
  <Router routes={routes}>
    <Suspense fallback={null}>
      <View />
    </Suspense>
  </Router>,
  document.getElementById('root'),
)
```

## Current behavior

The route associated with the "*" wildcard doesn't render. Instead, I get the following client-side error:

```
Uncaught NotFoundError: URL not found: /abouts
    at createNotFoundChunk (webpack-internal:///./node_modules/navi/dist/es/Chunks.js:27:16)
    at eval (webpack-internal:///./node_modules/navi/dist/es/createChunksMatcher.js:54:110)
    at step (webpack-internal:///./node_modules/navi/dist/es/createChunksMatcher.js:28:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/navi/dist/es/createChunksMatcher.js:9:53)
    at eval (webpack-internal:///./node_modules/navi/dist/es/Matcher.js:55:29)
    at step (webpack-internal:///./node_modules/navi/dist/es/Matcher.js:27:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/navi/dist/es/Matcher.js:8:53)
    at step (webpack-internal:///./node_modules/navi/dist/es/createChunksMatcher.js:13:139)
    at Object.eval [as next] (webpack-internal:///./node_modules/navi/dist/es/createChunksMatcher.js:9:53)
    at eval (webpack-internal:///./node_modules/navi/dist/es/Matcher.js:55:29)
```

Another error specifies that the previous one has originated from the `View` I have:

```
The above error occurred in the <View> component:
    in View
    in Suspense
    in HashScroll (created by NaviProvider)
    in NaviProvider (created by Router)
    in Router
```

**Comment by jamesknelson** [comment]
@kettanaito, is there any reason that `<NotFoundBoundary>` won't work for you?

https://frontarm.com/navi/en/reference/react-components-hooks/#notfoundboundary

**Comment by kettanaito** [comment]
Thanks, @jamesknelson. Adding error boundary has helped with the rendering part.

Hitting non-exiting URL still produces a chunk exception:

```
Uncaught NotFoundError: URL not found: /abouts
    at createNotFoundChunk (webpack-internal:///./node_modules/navi/dist/es/Chunks.js:27:16)
    at eval (webpack-internal:///./node_modules/navi/dist/es/matchers/mount.js:173:108)
    at step (webpack-internal:///./node_modules/navi/dist/es/matchers/mount.js:48:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/navi/dist/es/matchers/mount.js:29:53)
    at ChunkListObservable.refresh (webpack-internal:///./node_modules/navi/dist/es/ChunkListObservable.js:32:48)
    at ChunkListObservable.handleChange (webpack-internal:///./node_modules/navi/dist/es/ChunkListObservable.js:17:23)
    at ChunkListObservable.subscribe (webpack-internal:///./node_modules/navi/dist/es/ChunkListObservable.js:57:18)
    at Navigation.handleLocationChange (webpack-internal:///./node_modules/navi/dist/es/Navigation.js:338:54)
    at Navigation.refresh (webpack-internal:///./node_modules/navi/dist/es/Navigation.js:232:14)
```

Could you share with me what is the benefit of treating non-existing route like an exception, instead of a separate routing scenario?

**Comment by kettanaito** [comment]
Also, I don't know why but `<NotFoundBoundary>` doesn't seem to work during SSR.

I have something similar to this:

```jsx
// client/Root.jsx
import { View, NotFoundBoundary } from 'react-navi'
import Page404 from './pages/404/Page404'

const Root = () => (
  <NotFoundBoundary render={Page404}>
    <View />
  </NotFoundBoundary>
)
```

```jsx
// server/ssr.js
import Root from '@client/Root'

const clientMarkup = renderToString(
  <Router navigation={navigation}>
    <Root />
  </Router>,
)
```

That not found boundary declared on the client side and rendered on server doesn't suppress the actual error that happens when you hit a non-existing route. Rendering the components tree in that cases throws, and you need to handle it on the server explicitly. 

At the moment I check for the `error.status` and perform a manual redirect to the explicit `/404` route. But that's rather a compromise, since it loses the information about the original not found url.

**Comment by jamesknelson** [comment]
The reason for treating it as an exception up until now is that the way Navi works, a `mount()` near the top of the app doesn't know if a nested `mount()` doesn't find a match. E.g.

```js
mount({
  '/a': mount({
    '/b': route()
  })
})
```

If you try and route `/a/c` with this, the top mount sees `/a` and ignores the rest of the URL, leaving it to the child mount. Exceptions seemed to be a reasonable way to handle this.

There seem to be two issues with this approach, though.

1. create-react-app always shows an error screen, even if you properly catch and handle the exception.
2. `componentDidCatch` is not even supported by react-dom/server

Regarding issue 1, the CRA team told me at some point in the past that they'd fix this issue, but at this point it seems unlikely that it'll actually happen.

Regarding point 2, here's how I handle it in my own ssr app:

```js
  import { NotFoundError } from 'navi'

  try {
    // ...
  } catch (error) {
    if (error instanceof NotFoundError) {
      let html = template.replace('%RENDERED_CONTENT%', '')
      response.status(404).send(html)
      return
  )
}
```

Given that CRA doesn't seem to want to fix the error handling issue though, I'd definitely be open to changing all of this before the Navi 1.0. I'm just not sure on how else to approach it. Have you any suggestions?

**Comment by Springbach** [comment]
the same problem:
console:----------------------------------------------------------
Uncaught NotFoundError: URL not found: /about2
...
--------------------------------------------------------------------
Is there any way to use NotFoundBoundary without throwing NotFoundError exception in component?

**Comment by jamesknelson** [comment]
Not at the moment, unfortunately. It might be worth opening an issue on create react app, as I feel like showing an error screen even on handled errors is an issue there.
