### ISSUE TITLE
build failed on node >= 12

### ISSUE THREAD

**Issue by weihao** [frontarm/navi#198]
```
Find out more about deployment here:

  https://bit.ly/CRA-deploy

navi-scripts: Using config at C:\Users\forge\Documents\GitHub\navi.config.js
[ohshit] An error occured while building your app
Couldn't find window.NaviScripts - did you call register()?
Error: Couldn't find window.NaviScripts - did you call register()?
    at crawl (C:\Users\forge\Documents\GitHub\node_modules\navi-scripts\lib\crawl.js:22:15)
    at build (C:\Users\forge\Documents\GitHub\node_modules\navi-scripts\lib\build.js:9:32)
    at Command.<anonymous> (C:\Users\forge\Documents\GitHub\node_modules\navi-scripts\bin\navi-scripts.js:89:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I don't know why this is not resolved yet and no one is following up, but I want to bring this issue to the light again:

To reproduce this error just use any node version >= 12 and this error will encounter during the build phase.

Related to:
https://github.com/frontarm/navi/issues/92
https://github.com/frontarm/navi/issues/83

**Comment by mzvast** [comment]
Same here, need help
