### ISSUE TITLE
Server-side rendering example

### ISSUE THREAD

**Issue by kettanaito** [frontarm/navi#91]
Hello and thank you for a great library.

I'm going through the documentation and I cannot find a guide to have server-side rendering set up with `navi`. I'd like to help add one once I gain enough knowledge about the library's internals.

I've got a working SSR with `react-router` and when using `navi` I get the following exception on the server side:

```
ReferenceError: window is not defined
    at Object.createBrowserNavigation (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/navi/dist/commonjs/BrowserNavigation.js:26:58)
    at new Router (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/react-navi/dist/commonjs/Router.js:42:55)
    at processChild (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/react-dom/cjs/react-dom-server.node.development.js:2846:14)
    at resolve (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at app.get (webpack:///./src/server/middleware/ssr/index.js?:42:96)
    at Layer.handle [as handle_request] (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/artemzakharchenko/Documents/oss/unstack/node_modules/express/lib/router/route.js:137:13)
```

> I guess that's expected when creating browser navigation on the server :)

## Expected behavior

It would be great to have a contextless example of server-side rendering using `navi`. I would expect such example to include:

1. Explanation of steps required to perform SSR.
1. Code examples of SSR using client React application with `navi` as routing, and simple express (or other) NodeJS server that would be rendering our application.

Please let me know if I missed something, or can help with anything.

**Comment by jamesknelson** [comment]
I'm not 100% sure that the API is rock solid yet, so I'd like to hold off on proper documentation for a little longer. That said, the general idea is to just use `createMemoryNavigation()` instead of `createBrowserNavigation()`.

Here's the [docs for createMemoryNavigation()](https://frontarm.com/navi/en/reference/navigation/#creatememorynavigation).

For an example of how it all fits together, take a look at the [static rendering guide](https://frontarm.com/navi/en/guides/static-rendering/). Server rendering follows a pretty similar approach, except that instead of using `navi-scripts/register`, you'll need to have your build system produce a bundle targeting node, ala my [Create React App SSR PR](https://github.com/facebook/create-react-app/pull/6747).

**Comment by kettanaito** [comment]
Thanks for reply. Yeah, I've figure out some of the pieces already based on the static build. Yet it's confusing not to have a dedicated SSR section. Looking forward when the API is solid :) Let me know if I can help with anything.

**Comment by jamesknelson** [comment]
I'm really hoping to get the CRA SSR PR merged before finishing off Navi's SSR story. Or at least get a fork available based on the current PR -- the reason being that the build system is at least half the story to get it working right.

If you feel like you could give a hand with any of that, it'd be super useful!
